name: dynamic_matrix

on:
  - workflow_dispatch

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "build-matrix" 
        id: set-matrix
        run: |
          matrix=$(cat script/apps.json| jq -r -c '.apps|map(.target)|flatten|unique'| jq tostring)
          echo ${matrix}
          echo '::set-output name=build_target::${matrix}'
    outputs:
      build_target: ${{ steps.set-matrix.outputs.build_target }}
  build:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.build-matrix.outputs.build_target) }}
    steps:
      - uses: actions/checkout@v2